// Builds the desktop app for one game: generates the icon, stages the game's
// server + client + production deps, then runs electron-builder
// programmatically (avoids env-var plumbing differences between mac/win shells).
//
// Usage:
//   node scripts/build.js flotsam          # full installers for this platform
//   node scripts/build.js pulsar --dir     # unpacked dir only (fast, for smoke)
//
// Game can also come from env GAME (defaults to flotsam).
// Code signing is intentionally disabled — see README.md / STEAM.md.

'use strict';

const builder = require('electron-builder');
const GAMES = require('../games');
const { makeIcon } = require('./make-icons');
const { stageGame } = require('./stage-game');

const args = process.argv.slice(2);
const dirOnly = args.includes('--dir');
const gameId = args.find((a) => !a.startsWith('--')) || process.env.GAME || 'flotsam';
const cfg = GAMES[gameId];
if (!cfg) {
  console.error(`unknown game "${gameId}" (expected one of: ${Object.keys(GAMES).join(', ')})`);
  process.exit(1);
}

function buildConfig() {
  return {
    appId: cfg.appId,
    productName: cfg.productName,
    directories: {
      buildResources: `build/${gameId}`, // icon.png generated by make-icons.js
      output: `dist/${gameId}`,
    },
    files: ['main.js', 'games.js'],
    extraResources: [
      // staging/<game>/{meta.json,game/**} -> <resources>/{meta.json,game/**}
      { from: `staging/${gameId}`, to: '.' },
    ],
    asar: true,
    npmRebuild: false, // shell has no production deps; game deps staged separately
    mac: {
      category: 'public.app-category.games',
      target: [
        { target: 'dmg', arch: ['arm64'] },
        { target: 'zip', arch: ['arm64'] },
      ],
      identity: null, // no code signing for now (see STEAM.md)
      artifactName: '${productName}-${version}-${os}-${arch}.${ext}',
    },
    dmg: { sign: false },
    win: {
      target: [
        { target: 'nsis', arch: ['x64'] },
        { target: 'portable', arch: ['x64'] },
      ],
      // unsigned: no certificateFile / signing config on purpose
    },
    nsis: {
      oneClick: false,
      allowToChangeInstallationDirectory: true,
      artifactName: '${productName}-Setup-${version}.${ext}',
    },
    portable: {
      artifactName: '${productName}-${version}-portable.${ext}',
    },
  };
}

async function main() {
  console.log(`[build] game=${gameId} mode=${dirOnly ? 'dir (unpacked only)' : 'installers'}`);
  makeIcon(gameId);
  stageGame(gameId);

  const options = {
    config: buildConfig(),
    publish: 'never',
  };
  if (dirOnly) {
    // Unpacked dir for the current platform/arch — fast path for smoke tests.
    options.targets = builder.Platform.current().createTarget(builder.DIR_TARGET);
  }

  const artifacts = await builder.build(options);
  console.log('[build] artifacts:');
  for (const a of artifacts) console.log(`  ${a}`);
}

main().catch((err) => {
  console.error('[build] FAILED:', err);
  process.exit(1);
});
